# Generated by Django 4.1.5 on 2023-01-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bojId',
            field=models.TextField(null=True),
        ),
    ]
