# Generated by Django 4.1.5 on 2023-01-23 02:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boj', '0003_remove_member_lev0_remove_member_lev1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bojLev',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
