# Generated by Django 4.1.5 on 2023-01-23 02:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boj', '0004_alter_member_bojlev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bojLev',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], size=None),
        ),
    ]
