# Generated by Django 4.1.5 on 2023-01-23 02:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boj', '0005_alter_member_bojlev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bojLev',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], size=None),
        ),
    ]
