# Generated by Django 4.1.5 on 2023-01-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boj', '0006_alter_member_bojlev'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='setGoal',
            new_name='bojsetGoal',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='setLevel',
            new_name='bojsetLevel',
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.TextField(default='noname'),
        ),
    ]
