# Generated by Django 4.1.5 on 2023-01-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boj', '0007_rename_setgoal_member_bojsetgoal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='channelId',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberId',
            field=models.TextField(),
        ),
    ]
