# Generated by Django 4.1.5 on 2023-01-23 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boj', '0008_alter_member_channelid_alter_member_memberid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='channelId',
        ),
    ]
